version: 2.1
jobs:
  test-and-build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
  bump-version:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: Patch version & create version commit
          command: |
              git config --global user.email circleci@circleci
              git config --global user.name CircleCI
              npm version patch -m "v%s [skip ci]"
      - run:
          name: Push changes
          command: |
              git push
              git push --tags 
  deploy:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Install @viewar/cli
          command: sudo npm install -g @viewar/cli
      - run:
          name: Deploy
          command: viewar-cli deploy com.viewar.citest 20.0.0
workflows:
  version: 2
  test:
    jobs:
      - test-and-build
      - bump-version:
          requires:
           - test-and-build
          filters:
            branches:
              only: develop
      - deploy:
          requires:
           - bump-version
          filters:
            branches:
              only: develop
